{% set version = "1.4.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rtensor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rTensor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rTensor/rTensor_{{ version }}.tar.gz
  sha256: a8a12e050e881fa24568f362489f503a08160a8dcf356af09c25bdd06d91435e

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('rTensor')"           # [not win]
    - "\"%R%\" -e \"library('rTensor')\""  # [win]

about:
  home: https://github.com/rikenbit/rTensor
  license: GPL-2.0-or-later
  summary: A set of tools for creation, manipulation, and modeling of tensors with arbitrary number of modes. A tensor in the context of data analysis is a multidimensional array. rTensor does this by providing a S4 class 'Tensor' that wraps around the base 'array' class. rTensor provides common tensor operations as methods,
    including matrix unfolding, summing/averaging across modes, calculating the Frobenius norm, and taking the inner product between two tensors. Familiar array operations are overloaded, such as index subsetting via '[' and element-wise operations. rTensor also implements various tensor decomposition, including CP, GLRAM,
    MPCA, PVD, and Tucker. For tensors with 3 modes, rTensor also implements transpose, t-product, and t-SVD, as defined in Kilmer et al. (2013). Some auxiliary functions include the Khatri-Rao product, Kronecker product, and the Hadamard product for a list of matrices.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF
    - tbillet17

# Package: rTensor
# Type: Package
# Title: Tools for Tensor Analysis and Decomposition
# Version: 1.4.8
# Author: James Li and Jacob Bien and Martin Wells
# Maintainer: Koki Tsuyuzaki <k.t.the-answer@hotmail.co.jp>
# Description: A set of tools for creation, manipulation, and modeling of tensors with arbitrary number of modes. A tensor in the context of data analysis is a multidimensional array. rTensor does this by providing a S4 class 'Tensor' that wraps around the base 'array' class. rTensor provides common tensor operations as methods, including matrix unfolding, summing/averaging across modes, calculating the Frobenius norm, and taking the inner product between two tensors. Familiar array operations are overloaded, such as index subsetting via '[' and element-wise operations. rTensor also implements various tensor decomposition, including CP, GLRAM, MPCA, PVD, and Tucker. For tensors with 3 modes, rTensor also implements transpose, t-product, and t-SVD, as defined in Kilmer et al. (2013). Some auxiliary functions include the Khatri-Rao product, Kronecker product, and the Hadamard product for a list of matrices.
# License: GPL (>= 2)
# Depends: R (>= 2.10.0)
# Imports: methods
# Date: 2021-05-14
# URL: https://github.com/rikenbit/rTensor
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2021-05-14 04:43:12 UTC; root
# Repository: CRAN
# Date/Publication: 2021-05-15 06:20:10 UTC
